name: Run E2E Tests

on: [pull_request]

jobs: 
  run-e2e-tests: 
    name: Run E2E Test
    runs-on: ubuntu-latest  # ✅ Corrigido aqui

    services: 
      postgres: 
        image: bitnami/postgresql  # ✅ Corrigido indentação aqui
        ports: 
          - "5432:5432"
        env: 
          POSTGRESQL_USER: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: apisolid

    steps: 
      - uses: actions/checkout@v3  # ✅ Corrigido "users" para "uses"
      - uses: actions/setup-node@v3  
        with: 
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - run: npm run test:e2e
        env:
          JWT_SECRET: testing-secret
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"
